### ISSUE TITLE
Compile issue

### ISSUE THREAD

**Issue by Rexikon** [MitchDizzle/BlockMaker#5]
i'm compiling under debian 2.6.32-32 64x
root@dedi:~/addons/sourcemod/scripting# ./spcomp blockmaker.sp
SourcePawn Compiler 1.7.1-dev+5151
Copyright (c) 1997-2006 ITB CompuPhase
Copyright (c) 2004-2014 AlliedModders LLC

blockmaker.sp(124) : error 017: undefined symbol "editingBlock"
blockmaker.sp(124) : warning 215: expression has no effect
blockmaker.sp(124) : error 001: expected token: ";", but found "]"
blockmaker.sp(124) : error 029: invalid expression, assumed zero
blockmaker.sp(124) : fatal error 187: too many error messages on one line

Compilation aborted.
4 Errors.

How to fix it?

**Comment by MitchDizzle** [comment]
If you do not know how to fix this issue then you shouldn't be playing with this unfinished project. I don't know what you're hoping to achieve with this plugin as it stands, but i does not have any functionality.
